### PR TITLE
add new config "CtagsOptions"

### PR DESCRIPTION
**Pull request by Fmajor**
this should fix issue #13

### CODE REVIEW

**Comment by nicolashainaux** [comment]
This looks good 👍 
I will merge it.
Have you tested it with several arguments, like separated by commas? (If not, I think it's still easy to fix).

**Comment by Fmajor** [comment]
i did not make many tests, because this option is a global option.
if i can make different options for different file extensions, that will be better

**Comment by Fmajor** [comment]
i don't know what happened, but the plugin have different behavior in dev and normal mode
image
this is in dev mode (load plugin from my local dev folder)
the title "CtagsOptions" is right and it works

image
this is in normal mode (not in dev mode), i update the plugin to the latest version, but the configure title "Zz Ctags Options" is wrong, and the plugin does not work as i expect (the option is ignored).

**Comment by nicolashainaux** [comment]
Hum, I had no more time yesterday and couldn't publish it (I'll try asap but I don't want to publish in a hurry and make something wrong; I still need to merge it with other local changes and push everything back, add a description paragraph in the README and then publish).

So it's actually not a suprise that it's ignored in normal mode (it's just weird that the option still shows up in normal mode, I guess there's a little bug in atom).

**Comment by Fmajor** [comment]
that's weird...
I'm working on the dev mode, it's fine for me
take your time

**Pull request merged**
